### ISSUE TITLE
Changes required to install gact with pytorch 2.0 and cuda 11.8

### ISSUE THREAD

**Issue by apd10** [LiuXiaoxuanPKU/GACT-ICML#6]
Hi, 
     This is very interesting work. I am trying to install gact with pytorch 2.0 and cuda 11.8. I was able to install the gact repository with almost no change. (just had to change path of a include file). 
However, the benchmarks do not perform as expected like the gnn benchmark with L1 optimization 

 python3 test_gnn.py --model gcn --gact --level L1
Final Test Acc: 0.6555768162459108

I am guessing with pytorch 2.0, something funny happens. 
Do you have any pointers to debug to fix for pytorch 2.0?

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for your interest! According to [here](https://github.com/LiuXiaoxuanPKU/GACT-ICML/blob/5ddd88357bcf7ed8341a9b6a7be4a1ac4cdf88a9/gact/gact/conf.py#L13), L1 is fixed 4bit, which is one of the baselines. (The L1 is different from the L1 in the paper, sorry for the confusion. The L1 in the paper is actually the L2 in the code). Could you try with L2 
`python3 test_gnn.py --model gcn --gact --level L2`? The expected accuracy for OGBArxivDataset should be around 0.7 according to the paper.

**Comment by apd10** [comment]
That does make a lot of sense. 
python3 test_gnn.py --model gcn --gact --level L2
Final Test Acc : 0.716
This is inline with L1 in the paper. Thanks!

**Comment by apd10** [comment]
I tested with other configs as well. Thanks. Closing the issue.
